### ISSUE TITLE
For course with multiple lectures, all sections are in the last lecture

### ISSUE THREAD

**Issue by nitsanshai** [ScottyLabs/course-api#32]
``"21127": {``
``"lectures": [``
``{``
``"lecture": "Lec 1",``
``"sections": []``
``...``
``},``
``{``
``"lecture": "Lec 2",``
``"sections": [],``
``...``
``},``
``{"lecture": "Lec 3",``
``"sections": [``
``{"meetings": [{"begin": "12:30PM"...``

Obviously I reduced some of what my output was but I found that the sections are not in the appropriate lectures, for multiple courses I tried.

**Comment by justingallagher** [comment]
This actually seems to be a design error - if you look at [our source](https://enr-apps.as.cmu.edu/assets/SOC/sched_layout_spring.htm) for schedules, recitation sections aren't actually associated with specific lectures. It would make more sense to move them to a separate list (so we have a list of lectures and a list of sections).

**Comment by nitsanshai** [comment]
Yup just noticed that. Hmmm okay. I guess I'll have to work around this. Thanks!

**Comment by justingallagher** [comment]
I'm going to keep this open until I make that change - should be soon. Thanks for the report!

**Comment by justingallagher** [comment]
Fixed with #33. It's submitted to PyPi as version 1.0.0, as some API changes were made. Each course now contains a "sections" field that lists the recitations for each class. In addition, lectures and sections now carry a common structure with the fields: "times", listing meeting times; "name", listing the letter or lecture number of the meeting; and a list of the instructors.
