### ISSUE TITLE
Provide instructors' full names

### ISSUE THREAD

**Issue by justinchuby** [ScottyLabs/course-api#38]
It would be great if we can provide instructors' full names. An existing way of doing this is to infer names from the last name with a list of known names.

**Comment by justingallagher** [comment]
I'm not sure we have a feasible way to do this right now. Schedule data only supplies last names, which could result in collisions between instructors with the same last name. It gets more complicated when we have to deal with TAs too.

I'll leave this issue open in case we think of a better way, but I think we should hold off on this for now rather than risk having wrong or missing data.

**Comment by justinchuby** [comment]
Yeah. I agree with your point of not risking to have wrong data.
